name: YOLO Object Detection CI (Windows)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest   # 👈 switch from ubuntu to windows

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run YOLO tests
        run: python -m pytest -v   # 👈 safer way to call pytest on Windows
