name: Train YOLO on SageMaker (Windows)

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [ "main" ]

jobs:
  train:
    runs-on: windows-2025   # or windows-latest (2025 migration in progress)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # change region if needed

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 sagemaker awscli

      - name: Upload dataset to S3
        run: |
          aws s3 sync .\data\ s3://mcdyolobucket/ --recursive

      - name: Launch SageMaker training job
        run: python .\trainer_sm.py
